### ISSUE TITLE
Article comment font is small

### ISSUE THREAD

**Issue by vincode-io** [anosidium/About-HacKit#1]
I'd recommend making it a preference with maybe 5 different sizes where the system font size is the middle one. Right now people with visual impairments will have a hard time using the app.

Nice work on the app and I look forward to future updates!

**Comment by anosidium** [comment]
Thanks for your suggestion! I will implement this feature.

Glad you are looking forward to future updates, I do intend to improve it!

**Comment by anosidium** [comment]
I thought I would let you know that I have implemented this feature along with other features. The software update is out.

**Comment by vincode-io** [comment]
Thanks.  It looks much nicer now.
