### ISSUE TITLE
Search fails when made more specific

### ISSUE THREAD

**Issue by vincode-io** [anosidium/About-HacKit#2]
Searching for "NetNew" finds NetNewsWire, but "NewNews" doesn't.

<img width="1294" alt="Screen Shot 2021-01-24 at 4 59 58 PM" src="https://user-images.githubusercontent.com/16448027/105646486-db5dd680-5e65-11eb-9110-b7ec9081dea9.png">

<img width="1294" alt="Screen Shot 2021-01-24 at 5 00 33 PM" src="https://user-images.githubusercontent.com/16448027/105646492-e0228a80-5e65-11eb-9ecc-7e3b6ff71cf2.png">

**Comment by anosidium** [comment]
Interesting. I will investigate this.

**Comment by anosidium** [comment]
This has been fixed in 1.4. It should work for any search terms.
